apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.28.1
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yaml'
            - '--storage.path=/alertmanager'
            - '--web.external-url=https://alertmanager.thedrill.eu'
          ports:
            - containerPort: 9093
              name: alertmanager
              protocol: TCP
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: watch-pvc
              mountPath: /alertmanager
              subPath: alertmanager
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
        - name: watch-pvc
          persistentVolumeClaim:
            claimName: watch-pvc
