{
 "title": "(P) Air Quality",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "city", "query": { "query": "label_values(city)" } },
   { "name": "location", "query": { "query": "label_values(location)" } }
  ]
 },
 "panels": [
  {
   "title": "Temperature(T)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "C" } },
   "targets": [
    {
     "expr": "avg_over_time(air_quality_temperature{city=~\"$city\", location=~\"$location\", generic=\"true\"}[15m])",
     "legendFormat": "{{city}}/{{location}}"
    }
   ]
  },
  {
   "title": "Humidity(T)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "avg_over_time(air_quality_humidity{city=~\"$city\", location=~\"$location\", generic=\"true\"}[15m])",
     "legendFormat": "{{city}}/{{location}}"
    }
   ]
  },
  { "title": "Polution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Air Quality Index",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(air_quality_index{city=~\"$city\", location=~\"$location\", generic=\"false\"}[15m])",
     "legendFormat": "{{city}}/{{location}}"
    }
   ]
  },
  {
   "title": "Particle Matter(PM10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "expr": "avg_over_time(air_quality_pm10{city=~\"$city\", location=~\"$location\", generic=\"false\"}[15m])",
     "legendFormat": "{{city}}/{{location}}"
    }
   ]
  },
  {
   "title": "Particle Matter(PM2.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "expr": "avg_over_time(air_quality_pm25{city=~\"$city\", location=~\"$location\", generic=\"false\"}[15m])",
     "legendFormat": "{{city}}/{{location}}"
    }
   ]
  }
 ]
}