# This is for shared services that handle data storage and cache
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
# This is for shared services that handle communication between apps
apiVersion: v1
kind: Namespace
metadata:
  name: signal
---
# This is for shared services that handle monitoring and analysis of metrics
apiVersion: v1
kind: Namespace
metadata:
  name: watch
---
# This is for shared services that handle monitoring and analysis of metrics
apiVersion: v1
kind: Namespace
metadata:
  name: apps
