apiVersion: v1
kind: Service
metadata:
  name: paperless
spec:
  selector:
    app: paperless
  ports:
  - name: paperless
    port: 8000
    targetPort: paperless
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: apps-ipwhitelist@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - paperless.thedrill.eu
    secretName: paperless-tls
  rules:
  - host: paperless.thedrill.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperless
            port:
              number: 8000


