version: "3"

vars:
  OBSERVE_DIR: "{{.ROOT_DIR}}/k3s/observe"

tasks:
  _generic:
    internal: true
    silent: true
    dir: "{{.OBSERVE_DIR}}/{{.SERVICE}}"
    cmds:
      - echo "------------------------------"
      - echo "Applying {{.SERVICE}}"
      - echo "------------------------------"
      - kubectl apply -k .

  all:
    desc: Deploy observe layer
    silent: true
    cmds:
      - task: storage
      - echo ""
      - task: exporter-api
      - echo ""
      - task: exporter-snmp
      - echo ""
      - task: exporter-node
      - echo ""
      - task: victorialogs
      - echo ""
      - task: grafana
      - echo ""
      - task: prometheus
      - echo ""
      - task: alertmanager

  storage:
    dir: "{{.OBSERVE_DIR}}"
    silent: true
    cmds:
      - echo "------------------------------"
      - echo "Applying storage configuration"
      - echo "------------------------------"
      - kubectl apply -f storage.yaml

  grafana:
    vars:
      SERVICE: grafana
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

  prometheus:
    vars:
      SERVICE: prometheus
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

  alertmanager:
    vars:
      SERVICE: alertmanager
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

  victorialogs:
    vars:
      SERVICE: victorialogs
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

  exporter-node:
    vars:
      SERVICE: exporter-node
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

  exporter-api:
    vars:
      SERVICE: exporter-api
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"
           
  exporter-snmp:
    vars:
      SERVICE: exporter-snmp
    desc: Deploy {{.SERVICE}}
    cmds:
      - task: _generic
        vars:
          SERVICE: "{{.SERVICE}}"

    # desc: Deploy observe layer
    # dir: "{{.ROOT_DIR}}/k3s/observe"
    # cmds:
    #   - echo "Applying storage configuration"
    #   - kubectl apply -f storage.yaml
    #   - echo "Applying NodeExporter"
    #   - kubectl apply -k ./node-exporter 
    #   - echo "Applying APIExporter"
    #   - kubectl apply -k ./api-exporter 
    #   - echo "Applying SNMPExporter"
    #   - kubectl apply -k ./snmp-exporter 
    #   - echo "Applying Alertmanager"
    #   - kubectl apply -k ./alertmanager
    #   - echo "Applying Prometheus"
    #   - kubectl apply -k ./prometheus
    #   - echo "Applying Grafana"
    #   - kubectl apply -k ./grafana
    #
