apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  ports:
    - port: 5678
      protocol: TCP
      targetPort: n8n
  selector:
    app: n8n
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: apps-ipwhitelist@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - n8n.thedrill.eu
    secretName: n8n-tls
  rules:
    - host: n8n.thedrill.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
