---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  ports:
    - port: 5678
      protocol: TCP
      targetPort: n8n
  selector:
    app: n8n
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
  - host: n8n.thedrill.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 5678
