---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: grafana
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: watch-pvc
              mountPath: /var/lib/grafana
              subPath: grafana
            - name: grafana-datasources-config
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-dashboards-infra
              mountPath: /etc/grafana/provisioning/dashboards/infra
              readOnly: true
            - name: grafana-dashboards-root
              mountPath: /etc/grafana/provisioning/dashboards/root
              readOnly: true
      volumes:
        - name: grafana-datasources-config
          configMap:
            name: grafana-datasources-config
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: grafana-dashboards-root
          configMap:
            name: grafana-dashboards-root
        - name: grafana-dashboards-infra
          configMap:
            name: grafana-dashboards-infra
        - name: watch-pvc
          persistentVolumeClaim:
            claimName: watch-pvc
