apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  labels:
    app: snmp-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
        - name: snmp-exporter
          image: prom/snmp-exporter:v0.24.1
          args:
            - "--config.file=/etc/snmp_exporter/snmp.yml"
            - "--log.level=info"
          ports:
            - containerPort: 9116
              name: snmp-exporter
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: /etc/snmp_exporter
      volumes:
        - name: config
          configMap:
            name: snmp-exporter-config
