apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: watch

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: snmp-exporter-config
    files:
      - snmp.yml=configs/snmp.yaml

