{
 "title": "(P) Synology-NAS",
 "description": "Dashboard for viewing Synology System Information using Prometheus and SNMP_Exporter",
 "tags": [
  "synology",
  "dsm",
  "snmp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(modelName, instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(modelName, job)" } },
   { "name": "interfacebits", "query": "8" },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$job',instance=~'$instance'},ifName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Summary - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "System Temp",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100"
    }
   ]
  },
  {
   "title": "Hardware Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpuFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "powerStatus{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$job',instance=~'$instance',ifName=~'$Interface'}"
    },
    {
     "expr": "ifSpeed{job=~'$job',instance=~'$instance',ifName=~'$Interface'}"
    },
    {
     "expr": "ifOperStatus{job=~'$job',instance=~'$instance',ifName=~'$Interface'}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1-(raidFreeSize{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}/raidTotalSize{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}))*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "raidStatus{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskType{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskHealthStatus{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    },
    { "expr": "disk", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Connected Users / Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ssCpuUser{job=~'$job',instance=~'$instance'}",
       "legendFormat": "User"
      },
      {
       "expr": "ssCpuSystem{job=~'$job',instance=~'$instance'}",
       "legendFormat": "System"
      },
      {
       "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'} - ssCpuUser{job=~'$job',instance=~'$instance'} - ssCpuSystem{job=~'$job',instance=~'$instance'}",
       "legendFormat": "I/O Wait"
      }
     ]
    },
    {
     "title": "System Load (minute ave.) - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-1\"} / 100",
       "legendFormat": "{{laNames}}"
      },
      {
       "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-5\"} / 100",
       "legendFormat": "{{laNames}}"
      },
      {
       "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-15\"} / 100",
       "legendFormat": "{{laNames}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Utilisation - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})",
       "legendFormat": "Utilisation"
      }
     ]
    },
    {
     "title": "Physical Memory - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalReal{job=~'$job',instance=~'$instance'} ",
       "legendFormat": "Size"
      },
      {
       "expr": "memTotalReal{job=~'$job',instance=~'$instance'} - (memShared{job=~'$job',instance=~'$instance'} + memCached{job=~'$job',instance=~'$instance'} + memBuffer{job=~'$job',instance=~'$instance'} + memAvailReal{job=~'$job',instance=~'$instance'})",
       "legendFormat": "Reserved"
      },
      {
       "expr": "memBuffer{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "memCached{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Cached"
      },
      {
       "expr": "memShared{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Shared"
      },
      {
       "expr": "memAvailReal{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "SWAP Utilisation % - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100",
       "legendFormat": "Utilisation"
      }
     ]
    },
    {
     "title": "SWAP Utilisation - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Size"
      },
      {
       "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'})",
       "legendFormat": "Used"
      },
      {
       "expr": "memAvailSwap{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "HDD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Usage % - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
       "legendFormat": "Volume 1"
      },
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"})",
       "legendFormat": "Volume 2"
      },
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"})",
       "legendFormat": "Volume 3"
      },
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"})",
       "legendFormat": "Volume 4"
      },
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"})",
       "legendFormat": "Volume 5"
      },
      {
       "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"})",
       "legendFormat": "Volume 5"
      }
     ]
    },
    {
     "title": "Storage Usage - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}",
       "legendFormat": "Volume 1"
      },
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}",
       "legendFormat": "Volume 2"
      },
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}",
       "legendFormat": "Volume 3"
      },
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}",
       "legendFormat": "Volume 4"
      },
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}",
       "legendFormat": "Volume 5"
      },
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}",
       "legendFormat": "Volume 5"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host - Received Network Traffic - $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$job',instance=~'$instance',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    },
    {
     "title": "Host - Sent Network Traffic - $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCOutOctets{job=~'$job',instance=~'$instance',ifName=~'$Interface'}[$__rate_interval])*$interfacebits  ",
       "legendFormat": "{{label_name}}{{ifName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Exporter - Scrape Time - $instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "snmp_scrape_duration_seconds{job=~'$job',instance=~'$instance'}",
       "legendFormat": "{{label_name}}{{job}}"
      }
     ]
    }
   ]
  }
 ]
}