apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observe

resources:
  - deployment.yaml

configMapGenerator:
  - name: vmalert-rules
    files:
      - node-memory-alert.yaml=configs/node-memory-alert.yaml
