---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 65534
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
              name: prometheus
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: analytics-pvc
              mountPath: /prometheus
              subPath: prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: analytics-pvc
          persistentVolumeClaim:
            claimName: analytics-pvc
