---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: analytics
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: prometheus
  selector:
    app: prometheus
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: analytics
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
  - host: prometheus.thedrill.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
