global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kubernetes-cadvisor'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  # - job_name: 'kubernetes-pods'
  #   kubernetes_sd_configs:
  #   - role: pod
  #   relabel_configs:
  #   # Keep only pods with prometheus.io/scrape annotation
  #   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
  #     action: keep
  #     regex: true

  - job_name: 'k3s-nodes'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - infra
    relabel_configs:
      # Keep only node-exporter pods
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: node-exporter
        action: keep
      # Use node name as instance label
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: instance
      # Add namespace label
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      # Add pod name
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_(memory_MemAvailable_bytes|memory_MemTotal_bytes|load1|cpu_seconds_total|filesystem_size_bytes|filesystem_avail_bytes|hwmon_temp_celsius|hwmon_chip_names|scrape_collector_duration_seconds)'
        action: keep      

  # Air Quality monitoring 
  - job_name: 'air-quality'
    scrape_interval: 900s  # 15 minutes - be respectful of API limits
    scrape_timeout: 30s
    
    # Define each location as a separate target
    static_configs:
      - targets:
        - 'http://api.waqi.info/feed/@10564/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Plovdiv'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/@10091/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/@8090/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Burgas'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/A55669/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Lozenets'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A512740/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Bistrica'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A97348/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Pancharevo'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A185230/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Burgas'
          location: 'Vazrajdane'
          generic: false
      
    params:
      module: [air_quality]
    
    metrics_path: /probe

    relabel_configs:
      # Use the target URL as the parameter
      - source_labels: [__address__]
        target_label: __param_target
      
      # Point all requests to the json-exporter service
      - target_label: __address__
        replacement: api-exporter:7979
