---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-web
spec:
  selector:
    app: vaultwarden
  ports:
  - name: vaultwarden-web
    port: 8033
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vaultwarden.thedrill.eu
    secretName: vaultwarden-tls
  rules:
  - host: vaultwarden.thedrill.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden-web
            port:
              number: 8033


