apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bitcoin
                    operator: In
                    values:
                      - yes
      securityContext:
        runAsUser: 0
      containers:
        # - name: mempool
        #   image: mempool/mempool:v1.0k
        #   args:
        #     - "-printtoconsole"
        #     - "-conf=/etc/bitcoin.conf"
        #   volumeMounts:
        #     - name: ssd
        #       mountPath: /data
        #     - name: bitcoin-config
        #       mountPath: /etc/bitcoin.conf
        #       subPath: bitcoin.conf
        #     - name: apps-pvc
        #       mountPath: /home/bitcoin/.bitcoin
        #       subPath: bitcoin/data
        #   ports:
        #     - name: bitcoin-rpc
        #       containerPort: 8332
        #       protocol: TCP
        #     - name: bitcoin-main
        #       containerPort: 8333
        #       protocol: TCP
        - name: bitcoin
          image: bitcoinknots/bitcoin:latest
          args:
            - "-printtoconsole"
            - "-conf=/etc/bitcoin.conf"
          volumeMounts:
            - name: ssd
              mountPath: /data
            - name: bitcoin-config
              mountPath: /etc/bitcoin.conf
              subPath: bitcoin.conf
            # - name: apps-pvc
            #   mountPath: /home/bitcoin/.bitcoin
            #   subPath: bitcoin/data
          ports:
            - name: bitcoin-rpc
              containerPort: 8332
              protocol: TCP
            - name: bitcoin-main
              containerPort: 8333
              protocol: TCP
      volumes:
        - name: ssd
          hostPath:
            path: /mnt/ssd/bitcoin
            type: Directory
        - name: bitcoin-config
          configMap:
            name: bitcoin-config
        # - name: apps-pvc
        #   persistentVolumeClaim:
        #     claimName: apps-pvc
