apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: bitcoin
      #               operator: In
      #               values:
      #                 - yes
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "bitcoin"
        effect: "NoSchedule"
      securityContext:
        runAsUser: 0
      containers:
        - name: bitcoin
          image: bitcoinknots/bitcoin:latest
          args:
            - "-printtoconsole"
            - "-conf=/etc/bitcoin.conf"
          volumeMounts:
            - name: ssd
              mountPath: /home/bitcoin/.bitcoin
            - name: bitcoin-config
              mountPath: /etc/bitcoin.conf
              subPath: bitcoin.conf
          ports:
            - name: bitcoin-rpc
              containerPort: 8332
              protocol: TCP
            - name: bitcoin-main
              containerPort: 8333
              protocol: TCP
      volumes:
        - name: ssd
          hostPath:
            path: /mnt/ssd/bitcoin
            type: Directory
        - name: bitcoin-config
          configMap:
            name: bitcoin-config
