apiVersion: 1

deleteDatasources:
  - name: Alertmanager
    orgId: 1

datasources:
  - name: lab
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "60s"
      queryTimeout: "60s"
      httpMethod: POST
  - name: vlogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: false
    jsonData:
      maxLines: 1000
  - name: vmetrics
    uid: vmetrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://victoriametrics:8428
    editable: false
    jsonData:
      timeInterval: "60s"
      queryTimeout: "60s"
      httpMethod: POST
  # - name: Alertmanager
  #   uid: alertmanager
  #   type: alertmanager
  #   access: proxy
  #   url: http://alertmanager:9093
  #   editable: false
  #   jsonData:
  #     implementation: prometheus
  #     handleGrafanaManagedAlerts: false
