---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-infra
  namespace: infra
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-iscsi
  iscsi:
    targetPortal: 10.19.0.30:3260
    iqn: iqn.2025-08.local:k8s
    lun: 1 
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-pvc
  namespace: infra
spec:
  storageClassName: manual-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: iscsi-pv-infra



