-- Create resources for n8n app
CREATE DATABASE n8n;
CREATE USER n8n WITH PASSWORD 'n8n';
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;
\c n8n
ALTER DATABASE n8n OWNER TO n8n;
GRANT ALL ON SCHEMA public TO n8n;
GRANT CREATE ON SCHEMA public TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO n8n;

-- Create resources for mattermost app
CREATE DATABASE mattermost;
CREATE USER mattermost WITH PASSWORD 'mattermost';
GRANT ALL PRIVILEGES ON DATABASE mattermost TO mattermost;
\c mattermost
ALTER DATABASE mattermost OWNER TO mattermost;
GRANT ALL ON SCHEMA public TO mattermost;
GRANT CREATE ON SCHEMA public TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO mattermost;

-- Create resources for immich app
CREATE DATABASE immich;
CREATE USER immich WITH PASSWORD 'immich';
GRANT ALL PRIVILEGES ON DATABASE immich TO immich;
\c immich
ALTER DATABASE immich OWNER TO immich;
GRANT ALL ON SCHEMA public TO immich;
GRANT CREATE ON SCHEMA public TO immich;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO immich;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO immich;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO immich;


