apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.7.0.70/32  # Traefik
  - 10.7.0.250/32 # Not used
  - 10.7.0.251/32 # Not used
  - 10.7.0.252/32 # Not used
  - 10.7.0.253/32 # Bitcoin
  - 10.7.0.254/32 # DNS - Pihole

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: metallb-system
