apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: analytics

resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-datasources-config
    files:
      - datasource.yaml=configs/datasources.yaml
  - name: grafana-dashboards-config
    files:
      - dashboard.yaml=configs/dashboards.yaml
  - name: grafana-dashboards
    files:
      - air_quality.json=configs/dashboards/air_quality.json
      - k3s_nodes.json=configs/dashboards/k3s_nodes.json
