apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=configs/prometheus.yaml
