apiVersion: v1
kind: Service
metadata:
  name: victorialogs
spec:
  ports:
    - name: http
      port: 9428
      targetPort: http
  selector:
    app: victorialogs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victorialogs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vlogs.thedrill.eu
      secretName: victorialogs-tls
  rules:
    - host: vlogs.thedrill.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victorialogs
                port:
                  number: 9428
