apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      # Make sure that there is at max 1 pod on a node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pihole
            topologyKey: kubernetes.io/hostname
      containers:
        - name: pihole
          image: pihole/pihole:2025.08.0
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "nslookup google.com 127.0.0.1 || dig @127.0.0.1 google.com"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: pihole-env
            - secretRef:
                name: pihole-secrets
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 1Gi
          # volumeMounts:
          #   - name: apps-pvc
          #     mountPath: /etc/pihole
          #     subPath: pihole/config
      # volumes:
      #   - name: apps-pvc
      #     persistentVolumeClaim:
      #       claimName: apps-pvc
