apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yaml=configs/datasources.yaml

