---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-prometheus
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-iscsi
  iscsi:
    targetPortal: 10.19.0.30:3260
    iqn: iqn.2025-08.lab:apps
    lun: 2  # First LUN
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  storageClassName: manual-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  volumeName: iscsi-pv-prometheus

