---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: watch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # Multiple pods can read/write
  persistentVolumeReclaimPolicy: Retain
  storageClassName: watch
  nfs:
    server: storage.local.thedrill.eu
    path: /volume4/k8s/watch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watch-pvc 
  namespace: watch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: watch
  volumeName: watch-pv

