{
 "title": "(P) K3S-Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_hwmon_temp_celsius,instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_hwmon_temp_celsius,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (instance, job) (count by (instance, job, cpu) (node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "count by (instance, job) (count by (instance, job, cpu) (node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (1 - avg by (instance, job) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$__rate_interval]))) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (1 - avg by (instance, job) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$__rate_interval]))) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load1{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load1{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=~\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=~\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk(/)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  (node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - $node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "timeseries",
     "description": "System load average over 1, 5, and 15 minutes. Reflects the number of active or waiting processes. Values above CPU core count may indicate overload",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\",job=\"$job\"}",
       "legendFormat": "{{instance}} - Load(1m)"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))",
       "legendFormat": "CPU Core Count"
      }
     ]
    },
    {
     "title": "CPU Usage - $node",
     "type": "timeseries",
     "description": "System - Processes executing in kernel mode <br>\nUser - Processes executing in user mode <br>\nIOwait - Waiting for I/O to complete <br>\nNice - Niced processes executing in user mode <br>\nSteal - Time spent in other operating systems when in a VE <br>\nIrq - Servicing interrupts\n\n",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu,instance)))",
       "legendFormat": "Nice"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "IOwait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Irq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Softirq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Steal"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "User"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - $node",
     "type": "timeseries",
     "description": "RAM and swap usage overview, including caches",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 108 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}- node_memory_MemAvailable_bytes{instance=~\"$node\", job=\"$job\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "FileSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Used - $node",
     "type": "timeseries",
     "description": "Percentage of filesystem space used for each mounted device",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Available - $node",
     "type": "timeseries",
     "description": "Percentage of filesystem space used for each mounted device",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 131 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "description": "Monitors hardware sensor temperatures and critical thresholds as exposed by Linux hwmon. Includes CPU, GPU, and motherboard sensors where available",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max by (instance) (\n  node_hwmon_temp_celsius{instance=~\"$node\", job=~\"$job\"} \n  * on(chip, instance) group_left(chip_name) \n  node_hwmon_chip_names{instance=~\"$node\", job=~\"$job\"}\n)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "description": "Duration of each individual collector executed during a Node Exporter scrape. Useful for identifying slow or failing collectors",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (instance) (node_scrape_collector_duration_seconds{instance=~\"$node\",job=\"$job\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}