apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observe

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml

configMapGenerator:
  - name: victoriametrics-config
    files:
      - prometheus.yaml=configs/prometheus.yaml
