apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
spec:
  ports:
    - name: http
      port: 8428
      targetPort: http
  selector:
    app: victoriametrics
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoriametrics
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vmetrics.thedrill.eu
      secretName: victoriametrics-tls
  rules:
    - host: vmetrics.thedrill.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoriametrics
                port:
                  number: 8428
