global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Air Quality monitoring 
  - job_name: 'air-quality'
    scrape_interval: 900s  # 15 minutes - be respectful of API limits
    scrape_timeout: 30s
    
    # Define each location as a separate target
    static_configs:
      - targets:
        - 'http://api.waqi.info/feed/@10564/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Plovdiv'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/@10091/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/@8090/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Burgas'
          location: 'Center'
          generic: true
      - targets:
        - 'http://api.waqi.info/feed/A55669/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Lozenets'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A512740/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Bistrica'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A97348/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Sofia'
          location: 'Pancharevo'
          generic: false
      - targets:
        - 'http://api.waqi.info/feed/A185230/?token=c0c1906175267c768826e621f93a180f973d80ca'
        labels:
          country: 'Bulgaria'
          city: 'Burgas'
          location: 'Vazrajdane'
          generic: false
      
    params:
      module: [air_quality]
    
    metrics_path: /probe

    relabel_configs:
      # Use the target URL as the parameter
      - source_labels: [__address__]
        target_label: __param_target
      
      # Point all requests to the json-exporter service
      - target_label: __address__
        replacement: api-exporter:7979
