---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        envFrom:
        - configMapRef:
            name: postgres-env
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: infra-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d  # Special directory
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: infra-pvc
        persistentVolumeClaim:
          claimName: infra-pvc
      - name: postgres-init
        configMap:
          name: postgres-init
