apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: watch

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: api-exporter-config
    files:
      - config.yml=configs/config.yaml

